In [2]:
! pip install -q kaggle

In [3]:
# prompt: fix above problem

from google.colab import files

files.upload()

# Create a directory for Kaggle configuration files if it doesn't exist
!mkdir -p ~/.kaggle

!cp kaggle.json ~/.kaggle/
# Make the kaggle.json file executable (required by the Kaggle API)
!chmod 600 ~/.kaggle/kaggle.json

#! mkdir ~/.kaggle

!cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

Saving kaggle.json to kaggle (1).json

In [4]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
!kaggle competitions download -c superai5-esan-to-thai-machine-translation

superai5-esan-to-thai-machine-translation.zip: Skipping, found more recently modified local copy (use --force to force download)

In [6]:
!unzip superai5-esan-to-thai-machine-translation.zip

Archive:  superai5-esan-to-thai-machine-translation.zip
replace sample_submission.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: sample_submission.csv
  inflating: submission.csv
  inflating: test.csv
  inflating: train.csv
  inflating: val.csv

In [7]:
import warnings, os
warnings.filterwarnings('ignore')
os.environ["PYTHONWARNINGS"] = "ignore"

In [8]:
!nvidia-smi

Wed Jul  2 22:40:03 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   33C    P0             43W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [1]:
!pip install simpletransformers==0.70.1
!pip install transformers==4.51.1

Requirement already satisfied: simpletransformers==0.70.1 in /usr/local/lib/python3.11/dist-packages (0.70.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (2.32.3)
Requirement already satisfied: tqdm>=4.47.0 in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (4.67.1)
Requirement already satisfied: regex in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (2024.11.6)
Requirement already satisfied: transformers>=4.31.0 in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (4.51.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (2.14.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (1.15.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (1.6.1)
Requirement already satisfied: seqeval in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (1.2.2)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (2.18.0)
Requirement already satisfied: tensorboardx in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (2.6.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (2.2.2)
Requirement already satisfied: tokenizers in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (0.21.2)
Requirement already satisfied: wandb>=0.10.32 in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (0.20.1)
Requirement already satisfied: streamlit in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (1.46.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.11/dist-packages (from simpletransformers==0.70.1) (0.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers>=4.31.0->simpletransformers==0.70.1) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.31.0->simpletransformers==0.70.1) (0.33.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.31.0->simpletransformers==0.70.1) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.31.0->simpletransformers==0.70.1) (6.0.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.31.0->simpletransformers==0.70.1) (0.5.3)
Requirement already satisfied: click!=8.0.0,>=7.1 in /usr/local/lib/python3.11/dist-packages (from wandb>=0.10.32->simpletransformers==0.70.1) (8.2.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb>=0.10.32->simpletransformers==0.70.1) (3.1.44)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.11/dist-packages (from wandb>=0.10.32->simpletransformers==0.70.1) (4.3.8)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /usr/local/lib/python3.11/dist-packages (from wandb>=0.10.32->simpletransformers==0.70.1) (5.29.5)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb>=0.10.32->simpletransformers==0.70.1) (5.9.5)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.11/dist-packages (from wandb>=0.10.32->simpletransformers==0.70.1) (2.11.7)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb>=0.10.32->simpletransformers==0.70.1) (2.32.0)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.11/dist-packages (from wandb>=0.10.32->simpletransformers==0.70.1) (1.3.6)
Requirement already satisfied: typing-extensions<5,>=4.8 in /usr/local/lib/python3.11/dist-packages (from wandb>=0.10.32->simpletransformers==0.70.1) (4.14.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->simpletransformers==0.70.1) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->simpletransformers==0.70.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->simpletransformers==0.70.1) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->simpletransformers==0.70.1) (2025.6.15)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets->simpletransformers==0.70.1) (18.1.0)
Requirement already satisfied: dill<0.3.8,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets->simpletransformers==0.70.1) (0.3.7)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets->simpletransformers==0.70.1) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from datasets->simpletransformers==0.70.1) (0.70.15)
Requirement already satisfied: fsspec>=2021.11.1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.11.1->datasets->simpletransformers==0.70.1) (2025.3.2)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets->simpletransformers==0.70.1) (3.11.15)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->simpletransformers==0.70.1) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->simpletransformers==0.70.1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->simpletransformers==0.70.1) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->simpletransformers==0.70.1) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->simpletransformers==0.70.1) (3.6.0)
Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit->simpletransformers==0.70.1) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from streamlit->simpletransformers==0.70.1) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.11/dist-packages (from streamlit->simpletransformers==0.70.1) (5.5.2)
Requirement already satisfied: pillow<12,>=7.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit->simpletransformers==0.70.1) (11.2.1)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from streamlit->simpletransformers==0.70.1) (8.5.0)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from streamlit->simpletransformers==0.70.1) (0.10.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.11/dist-packages (from streamlit->simpletransformers==0.70.1) (6.0.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.11/dist-packages (from streamlit->simpletransformers==0.70.1) (0.9.1)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.11/dist-packages (from streamlit->simpletransformers==0.70.1) (6.4.2)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.11/dist-packages (from tensorboard->simpletransformers==0.70.1) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.11/dist-packages (from tensorboard->simpletransformers==0.70.1) (1.73.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard->simpletransformers==0.70.1) (3.8.2)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard->simpletransformers==0.70.1) (75.2.0)
Requirement already satisfied: six>1.9 in /usr/local/lib/python3.11/dist-packages (from tensorboard->simpletransformers==0.70.1) (1.17.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard->simpletransformers==0.70.1) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard->simpletransformers==0.70.1) (3.1.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit->simpletransformers==0.70.1) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit->simpletransformers==0.70.1) (4.24.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.11/dist-packages (from altair<6,>=4.0->streamlit->simpletransformers==0.70.1) (1.45.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->simpletransformers==0.70.1) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->simpletransformers==0.70.1) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->simpletransformers==0.70.1) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->simpletransformers==0.70.1) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->simpletransformers==0.70.1) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->simpletransformers==0.70.1) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets->simpletransformers==0.70.1) (1.20.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb>=0.10.32->simpletransformers==0.70.1) (4.0.12)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers>=4.31.0->simpletransformers==0.70.1) (1.1.5)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3->wandb>=0.10.32->simpletransformers==0.70.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3->wandb>=0.10.32->simpletransformers==0.70.1) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3->wandb>=0.10.32->simpletransformers==0.70.1) (0.4.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard->simpletransformers==0.70.1) (3.0.2)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb>=0.10.32->simpletransformers==0.70.1) (5.0.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->simpletransformers==0.70.1) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->simpletransformers==0.70.1) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit->simpletransformers==0.70.1) (0.26.0)
Requirement already satisfied: transformers==4.51.1 in /usr/local/lib/python3.11/dist-packages (4.51.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers==4.51.1) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers==4.51.1) (0.33.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.51.1) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers==4.51.1) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.51.1) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.51.1) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers==4.51.1) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers==4.51.1) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers==4.51.1) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers==4.51.1) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.51.1) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.51.1) (4.14.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.51.1) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.51.1) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.51.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.51.1) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.51.1) (2025.6.15)

In [9]:
import logging
import pandas as pd
from simpletransformers.seq2seq import Seq2SeqModel, Seq2SeqArgs
import torch, os

os.environ["TOKENIZERS_PARALLELISM"] = "false"

os.system("rm -rf outputs/ cache_dir/ runs/")

# Setup logging
logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

# Load and prepare the datasets
train_df = pd.read_csv("train.csv")
val_df = pd.read_csv("val.csv")

# Rename columns
train_df = train_df.rename(columns={"input": "input_text", "output": "target_text"})
val_df = val_df.rename(columns={"input": "input_text", "output": "target_text"})

# Remove '\n' from text
train_df["input_text"] = train_df["input_text"].str.replace("\n", "", regex=False)
train_df["target_text"] = train_df["target_text"].str.replace("\n", "", regex=False)
val_df["input_text"] = val_df["input_text"].str.replace("\n", "", regex=False)
val_df["target_text"] = val_df["target_text"].str.replace("\n", "", regex=False)

train_df = train_df[["input_text", "target_text"]]
val_df = val_df[["input_text", "target_text"]]

full = pd.concat([train_df, val_df])
full

,input_text,target_text
0,คึดฮอดเจ้าหลายเด้อ,คิดถึงเธอมากนะ
1,เจ้าสิไปเบิ่งคอนเสิร์ตหมอลำซิ่งนำกันบ่มื้อนี้แลง,คุณจะไปดูคอนเสิร์ตหมอลำซิ่งด้วยกันไหมเย็นนี้
2,เฮาสิไปเลาะในเมือง,เราจะไปเดินเล่นในเมือง
3,เฮามาเฮ็ดแนวกินนำกัน,เรามาทำอาหารด้วยกัน
4,เมื่อวานเฮาไปฟังหมอลำหน้าวัดม่วนหลายสนุกจนบ่มี...,เมื่อวานเราไปฟังหมอลำหน้าวัดสนุกมากจนไม่มีใครอ...
...,...,...
107,ข่อยคิดฮอดอิแม่แฮง,ฉันคิดถึงแม่มาก
108,ซื้อสองชิ้นลดบ่,ซื้อสองชิ้นลดไหม
109,เงินเดือนขึ้นบ่,เงินเดือนขึ้นไหม
110,ไปเถาะอย่ารอหลาย,ไปเถอะอย่ารอนาน
111,ให้ข่อยซ่อยเจ้าแนบ่,ให้ฉันช่วยคุณหน่อยไหม

In [10]:
# Define model arguments
model_args = {
    "overwrite_output_dir": True,
    "num_train_epochs": 5,
    "gradient_accumulation_steps": 2,
    "train_batch_size": 8,
    "max_seq_length": 64,
    'n_gpu': 1,
}

# Initialize the model
model = Seq2SeqModel(
    encoder_decoder_type="mbart",
    encoder_decoder_name="facebook/mbart-large-50-many-to-many-mmt",
    max_length=64,
    args=model_args,
)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'MBart50Tokenizer'.
The class this function is called from is 'MBartTokenizer'.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'MBart50Tokenizer'.
The class this function is called from is 'MBartTokenizerFast'.

In [11]:
# Train the model
model.train_model(train_df)

  0%|          | 0/1943 [00:00<?, ?it/s]

Epoch:   0%|          | 0/5 [00:00<?, ?it/s]

Running Epoch 1 of 5:   0%|          | 0/243 [00:00<?, ?it/s]

Running Epoch 2 of 5:   0%|          | 0/243 [00:00<?, ?it/s]

Running Epoch 3 of 5:   0%|          | 0/243 [00:00<?, ?it/s]

Running Epoch 4 of 5:   0%|          | 0/243 [00:00<?, ?it/s]

Running Epoch 5 of 5:   0%|          | 0/243 [00:00<?, ?it/s]

(605, 1.4880535423509345)

In [12]:
test_df = pd.read_csv("test.csv")
test_df["input"] = test_df["input"].str.replace("\n", "", regex=False)
test_df

       id                        input
0    2055             ข่อยบ่มีเวลาหลาย
1    2056    บ่ฮู้ว่าสิใช้แอปนี้จั่งใด
2    2057         เจ้ามีเบอร์โทรข่อยบ่
3    2058          เฮามาสิลองเฮ็ดเบิ่ง
4    2059                ไปนอนก่อนเด้อ
..    ...                          ...
369  2424    กาแฟสิใช้เมล็ดจากบราซิลบ่
370  2425  ถ้าซื้อหลายชิ้นลดเพิ่มได้บ่
371  2426                เจ้าคิดจังได๋
372  2427             เฮ็ดเวียกอยู่บ้อ
373  2428              ซ่อยข่อยยกของแน

[374 rows x 2 columns]

In [13]:
!pip install -q pythainlp

In [14]:
from pythainlp.tokenize import word_tokenize

submission = pd.read_csv('sample_submission.csv')
submission['output'] = model.predict(test_df['input'].tolist())
submission['output'] = submission['output'].apply(lambda x: ' '.join(word_tokenize(x, engine="newmm")))
submission.to_csv('submission.csv', index=False)
submission

Generating outputs:   0%|          | 0/4 [00:00<?, ?it/s]

       id                                   output
0    2055                      ฉัน ไม่ มี เวลา มาก
1    2056   ไม่ รู้ ว่า จะ ซื้อ แอ ป นี้ เมื่อไหร่
2    2057                 เธอ มี เบอร์ โทร ฉัน ไหม
3    2058                     เรา จะ มา ลอง ทํา ดู
4    2059                           ไป นอน ก่อน นะ
..    ...                                      ...
369  2424         กาแฟ จะ ใช้ เมล็ด จาก บราซิล ไหม
370  2425  ต้อง ซื้อ เยอะ มาก เลย ลด เพิ่ม ได้ ไหม
371  2426                            เธอ คิด ยังไง
372  2427                       ทํา งาน อยู่ บ ไหม
373  2428                    ช่วย ฉัน ยก ของ หน่อย

[374 rows x 2 columns]

In [ ]:
#kaggle competitions submit -c superai5-esan-to-thai-machine-translation -f submission.csv -m "Message"

In [15]:
!pip list | grep transformers

sentence-transformers                 4.1.0
simpletransformers                    0.70.1
transformers                          4.51.1

In [16]:
submission.to_csv('submission.csv', index=False)

In [17]:
!kaggle competitions submit -c superai5-esan-to-thai-machine-translation -f submission.csv -m "Message"

100% 27.2k/27.2k [00:00<00:00, 72.3kB/s]
Successfully submitted to ESAN to THAI Machine Translation